-- MySQL Script generated by MySQL Workbench
-- Wed Nov 27 03:03:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hospitaldb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hospitaldb` ;

-- -----------------------------------------------------
-- Schema hospitaldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospitaldb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hospitaldb` ;

-- -----------------------------------------------------
-- Table `hospitaldb`.`patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitaldb`.`patients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `birth_date` DATE NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `gender` ENUM('Male', 'Female') NULL DEFAULT NULL,
  `interests` TEXT NULL DEFAULT NULL,
  `vk_profile` VARCHAR(255) NULL DEFAULT NULL,
  `blood_type` VARCHAR(3) NULL DEFAULT NULL,
  `rh_factor` ENUM('+', '-') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospitaldb`.`diseases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitaldb`.`diseases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospitaldb`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitaldb`.`tests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `disease_id` INT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `disease_id` (`disease_id` ASC) VISIBLE,
  CONSTRAINT `tests_ibfk_1`
    FOREIGN KEY (`disease_id`)
    REFERENCES `hospitaldb`.`diseases` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospitaldb`.`analyzes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitaldb`.`analyzes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `patients_id` INT NOT NULL,
  `tests_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `results` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_patients_has_tests_tests1_idx` (`tests_id` ASC) VISIBLE,
  INDEX `fk_patients_has_tests_patients1_idx` (`patients_id` ASC) VISIBLE,
  CONSTRAINT `fk_patients_has_tests_patients1`
    FOREIGN KEY (`patients_id`)
    REFERENCES `hospitaldb`.`patients` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_patients_has_tests_tests1`
    FOREIGN KEY (`tests_id`)
    REFERENCES `hospitaldb`.`tests` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospitaldb`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitaldb`.`doctors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NOT NULL,
  `specialization` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospitaldb`.`wards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitaldb`.`wards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ward_number` INT NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospitaldb`.`sickleaves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitaldb`.`sickleaves` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `patient_id` INT NOT NULL,
  `doctor_id` INT NOT NULL,
  `wards_id` INT NOT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `reason` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `patient_id` (`patient_id` ASC) VISIBLE,
  INDEX `doctor_id` (`doctor_id` ASC) VISIBLE,
  INDEX `fk_sickleaves_wards1_idx` (`wards_id` ASC) VISIBLE,
  CONSTRAINT `fk_sickleaves_wards1`
    FOREIGN KEY (`wards_id`)
    REFERENCES `hospitaldb`.`wards` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `sickleaves_ibfk_1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `hospitaldb`.`patients` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `sickleaves_ibfk_2`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `hospitaldb`.`doctors` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
